# Change these first
owner: Frank-Vu # Your GitHub organization or username, where this repository lives
repo: frankvu-upptime # The name of this repository

sites:
  - name: FrankVu
    url: https://www.frankvu.site
  - name: Wedding Site
    url: https://www.giang-jess.frankvu.site

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.frankvu.site
  # baseUrl: /frankvu-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: FrankVu Upptime
  introTitle: "**FrankVu UppTime** is the uptime monitor and status page for FrankVu personal websites and projects."
  introMessage: This uptime monitor and status page is from the open-source [Upptime](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Personal Site
      href: https://www.frankvu.site
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
